@startuml
'https://plantuml.com/class-diagram

class Motor{
    --Atributs--
    --Metodes--
}

class Bateria{
    --Atributs--
    --Metodes--
}

class Dron{
    --Atributs--
    --Metodes--
}
@enduml